//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente_Calcula.calcularArea {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="calcularArea.CalcularSoap")]
    public interface CalcularSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CREADORResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CREADOR", ReplyAction="*")]
        Cliente_Calcula.calcularArea.CREADORResponse CREADOR(Cliente_Calcula.calcularArea.CREADORRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CREADOR", ReplyAction="*")]
        System.Threading.Tasks.Task<Cliente_Calcula.calcularArea.CREADORResponse> CREADORAsync(Cliente_Calcula.calcularArea.CREADORRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CUADRADO", ReplyAction="*")]
        int CUADRADO(int Lado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CUADRADO", ReplyAction="*")]
        System.Threading.Tasks.Task<int> CUADRADOAsync(int Lado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TRIANGULO", ReplyAction="*")]
        int TRIANGULO(int Base, int Altura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TRIANGULO", ReplyAction="*")]
        System.Threading.Tasks.Task<int> TRIANGULOAsync(int Base, int Altura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CIRCULO", ReplyAction="*")]
        double CIRCULO(double Radio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CIRCULO", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CIRCULOAsync(double Radio);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CREADORRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CREADOR", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_Calcula.calcularArea.CREADORRequestBody Body;
        
        public CREADORRequest() {
        }
        
        public CREADORRequest(Cliente_Calcula.calcularArea.CREADORRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CREADORRequestBody {
        
        public CREADORRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CREADORResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CREADORResponse", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_Calcula.calcularArea.CREADORResponseBody Body;
        
        public CREADORResponse() {
        }
        
        public CREADORResponse(Cliente_Calcula.calcularArea.CREADORResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CREADORResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CREADORResult;
        
        public CREADORResponseBody() {
        }
        
        public CREADORResponseBody(string CREADORResult) {
            this.CREADORResult = CREADORResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalcularSoapChannel : Cliente_Calcula.calcularArea.CalcularSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcularSoapClient : System.ServiceModel.ClientBase<Cliente_Calcula.calcularArea.CalcularSoap>, Cliente_Calcula.calcularArea.CalcularSoap {
        
        public CalcularSoapClient() {
        }
        
        public CalcularSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalcularSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcularSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcularSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente_Calcula.calcularArea.CREADORResponse Cliente_Calcula.calcularArea.CalcularSoap.CREADOR(Cliente_Calcula.calcularArea.CREADORRequest request) {
            return base.Channel.CREADOR(request);
        }
        
        public string CREADOR() {
            Cliente_Calcula.calcularArea.CREADORRequest inValue = new Cliente_Calcula.calcularArea.CREADORRequest();
            inValue.Body = new Cliente_Calcula.calcularArea.CREADORRequestBody();
            Cliente_Calcula.calcularArea.CREADORResponse retVal = ((Cliente_Calcula.calcularArea.CalcularSoap)(this)).CREADOR(inValue);
            return retVal.Body.CREADORResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente_Calcula.calcularArea.CREADORResponse> Cliente_Calcula.calcularArea.CalcularSoap.CREADORAsync(Cliente_Calcula.calcularArea.CREADORRequest request) {
            return base.Channel.CREADORAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente_Calcula.calcularArea.CREADORResponse> CREADORAsync() {
            Cliente_Calcula.calcularArea.CREADORRequest inValue = new Cliente_Calcula.calcularArea.CREADORRequest();
            inValue.Body = new Cliente_Calcula.calcularArea.CREADORRequestBody();
            return ((Cliente_Calcula.calcularArea.CalcularSoap)(this)).CREADORAsync(inValue);
        }
        
        public int CUADRADO(int Lado) {
            return base.Channel.CUADRADO(Lado);
        }
        
        public System.Threading.Tasks.Task<int> CUADRADOAsync(int Lado) {
            return base.Channel.CUADRADOAsync(Lado);
        }
        
        public int TRIANGULO(int Base, int Altura) {
            return base.Channel.TRIANGULO(Base, Altura);
        }
        
        public System.Threading.Tasks.Task<int> TRIANGULOAsync(int Base, int Altura) {
            return base.Channel.TRIANGULOAsync(Base, Altura);
        }
        
        public double CIRCULO(double Radio) {
            return base.Channel.CIRCULO(Radio);
        }
        
        public System.Threading.Tasks.Task<double> CIRCULOAsync(double Radio) {
            return base.Channel.CIRCULOAsync(Radio);
        }
    }
}
